@startuml packages
set namespaceSeparator none
package "aulos" as aulos {
}
package "aulos.TET12" as aulos.TET12 {
}
package "aulos.TET12.note" as aulos.TET12.note {
}
package "aulos.TET12.scale" as aulos.TET12.scale {
}
package "aulos.TET12.tuner" as aulos.TET12.tuner {
}
package "aulos.TET12.utils" as aulos.TET12.utils {
}
package "aulos.__main__" as aulos.__main__ {
}
package "aulos._core" as aulos._core {
}
package "aulos._core.framework" as aulos._core.framework {
}
package "aulos._core.framework.context" as aulos._core.framework.context {
}
package "aulos._core.framework.derivedcache" as aulos._core.framework.derivedcache {
}
package "aulos._core.framework.inject" as aulos._core.framework.inject {
}
package "aulos._core.framework.instancecache" as aulos._core.framework.instancecache {
}
package "aulos._core.framework.optimize" as aulos._core.framework.optimize {
}
package "aulos._core.object" as aulos._core.object {
}
package "aulos._core.schema" as aulos._core.schema {
}
package "aulos._core.setting" as aulos._core.setting {
}
package "aulos._core.utils" as aulos._core.utils {
}
package "aulos._core.utils.array" as aulos._core.utils.array {
}
package "aulos._core.utils.calculation" as aulos._core.utils.calculation {
}
package "aulos._core.utils.dataclass" as aulos._core.utils.dataclass {
}
package "aulos._core.utils.decorators" as aulos._core.utils.decorators {
}
package "aulos._version" as aulos._version {
}
package "aulos.chord" as aulos.chord {
}
package "aulos.chord.chord" as aulos.chord.chord {
}
package "aulos.chord.quality" as aulos.chord.quality {
}
package "aulos.note" as aulos.note {
}
package "aulos.note.key" as aulos.note.key {
}
package "aulos.note.note" as aulos.note.note {
}
package "aulos.note.pitchclass" as aulos.note.pitchclass {
}
package "aulos.note.schemas" as aulos.note.schemas {
}
package "aulos.note.schemas.key" as aulos.note.schemas.key {
}
package "aulos.note.schemas.note" as aulos.note.schemas.note {
}
package "aulos.note.schemas.pitchclass" as aulos.note.schemas.pitchclass {
}
package "aulos.scale" as aulos.scale {
}
package "aulos.scale.diatonic" as aulos.scale.diatonic {
}
package "aulos.scale.scale" as aulos.scale.scale {
}
package "aulos.scale.schemas" as aulos.scale.schemas {
}
package "aulos.tuner" as aulos.tuner {
}
package "aulos.tuner.schemas" as aulos.tuner.schemas {
}
package "aulos.tuner.tuner" as aulos.tuner.tuner {
}
package "aulos.ui" as aulos.ui {
}
package "aulos.ui.components" as aulos.ui.components {
}
package "aulos.ui.components.base" as aulos.ui.components.base {
}
package "aulos.ui.components.keyboard" as aulos.ui.components.keyboard {
}
package "aulos.ui.components.scaleviewer" as aulos.ui.components.scaleviewer {
}
package "aulos.ui.components.selecter" as aulos.ui.components.selecter {
}
package "aulos.ui.components.selecter.keyselecter" as aulos.ui.components.selecter.keyselecter {
}
package "aulos.ui.components.selecter.scaleselecter" as aulos.ui.components.selecter.scaleselecter {
}
package "aulos.ui.main" as aulos.ui.main {
}
package "aulos.utils" as aulos.utils {
}
package "aulos.utils.aulos" as aulos.utils.aulos {
}
package "aulos.utils.context" as aulos.utils.context {
}
package "aulos.utils.track" as aulos.utils.track {
}
aulos --> aulos._core
aulos --> aulos._version
aulos --> aulos.note
aulos --> aulos.scale
aulos --> aulos.tuner
aulos.TET12 --> aulos.TET12.tuner
aulos.TET12 --> aulos.note
aulos.TET12 --> aulos.scale
aulos.TET12.note --> aulos.TET12.note
aulos.TET12.scale --> aulos.TET12.note
aulos.TET12.scale --> aulos.TET12.scale
aulos.TET12.tuner --> aulos.TET12.note
aulos.TET12.tuner --> aulos.TET12.tuner
aulos.TET12.tuner --> aulos.TET12.utils
aulos.__main__ --> aulos.ui
aulos._core --> aulos._core.object
aulos._core --> aulos._core.schema
aulos._core --> aulos._core.setting
aulos._core.framework --> aulos._core.framework.context
aulos._core.framework --> aulos._core.framework.derivedcache
aulos._core.framework --> aulos._core.framework.inject
aulos._core.framework --> aulos._core.framework.instancecache
aulos._core.framework --> aulos._core.framework.optimize
aulos._core.framework.inject --> aulos._core.framework.context
aulos._core.object --> aulos._core.framework
aulos._core.object --> aulos._core.schema
aulos._core.object --> aulos._core.setting
aulos._core.object --> aulos._core.utils
aulos._core.setting --> aulos._core.utils
aulos._core.utils --> aulos._core.utils.array
aulos._core.utils --> aulos._core.utils.calculation
aulos._core.utils --> aulos._core.utils.dataclass
aulos._core.utils --> aulos._core.utils.decorators
aulos.chord --> aulos.chord.chord
aulos.chord.chord --> aulos.chord.quality
aulos.note --> aulos.note.key
aulos.note --> aulos.note.note
aulos.note --> aulos.note.pitchclass
aulos.note.key --> aulos.note.pitchclass
aulos.note.key --> aulos.note.schemas
aulos.note.note --> aulos.note.pitchclass
aulos.note.note --> aulos.note.schemas
aulos.note.pitchclass --> aulos.note.schemas
aulos.note.schemas --> aulos.note.key
aulos.note.schemas --> aulos.note.note
aulos.note.schemas --> aulos.note.pitchclass
aulos.note.schemas.key --> aulos.note.schemas.pitchclass
aulos.note.schemas.note --> aulos.note.schemas.pitchclass
aulos.scale --> aulos.scale.diatonic
aulos.scale --> aulos.scale.scale
aulos.scale.diatonic --> aulos.scale.scale
aulos.scale.scale --> aulos.scale.schemas
aulos.scale.schemas --> aulos.scale.scale
aulos.tuner --> aulos.tuner.tuner
aulos.tuner.schemas --> aulos.tuner.tuner
aulos.tuner.tuner --> aulos.tuner.schemas
aulos.ui --> aulos.ui.components
aulos.ui --> aulos.ui.main
aulos.ui.components --> aulos.ui.components.keyboard
aulos.ui.components --> aulos.ui.components.scaleviewer
aulos.ui.components.scaleviewer --> aulos.ui.components.base
aulos.ui.components.scaleviewer --> aulos.ui.components.selecter
aulos.ui.components.selecter --> aulos.ui.components.selecter.keyselecter
aulos.ui.components.selecter --> aulos.ui.components.selecter.scaleselecter
aulos.ui.main --> aulos.ui.components
aulos.utils --> aulos
aulos.utils.aulos --> aulos.utils.context
aulos.utils.aulos --> aulos.utils.track
@enduml
