@startuml packages
set namespaceSeparator none
package "aulos" as aulos {
}
package "aulos.__main__" as aulos.__main__ {
}
package "aulos._core" as aulos._core {
}
package "aulos._core.coexistence" as aulos._core.coexistence {
}
package "aulos._core.context" as aulos._core.context {
}
package "aulos._core.context._inject" as aulos._core.context._inject {
}
package "aulos._core.interfaces" as aulos._core.interfaces {
}
package "aulos._core.interfaces.ring" as aulos._core.interfaces.ring {
}
package "aulos._core.object" as aulos._core.object {
}
package "aulos._core.schema" as aulos._core.schema {
}
package "aulos._core.setting" as aulos._core.setting {
}
package "aulos._core.shared" as aulos._core.shared {
}
package "aulos._core.shared.intervals" as aulos._core.shared.intervals {
}
package "aulos._core.utils" as aulos._core.utils {
}
package "aulos._core.utils.array" as aulos._core.utils.array {
}
package "aulos._core.utils.calculation" as aulos._core.utils.calculation {
}
package "aulos._core.utils.decorators" as aulos._core.utils.decorators {
}
package "aulos._core.utils.dict" as aulos._core.utils.dict {
}
package "aulos._errors" as aulos._errors {
}
package "aulos._version" as aulos._version {
}
package "aulos._warnings" as aulos._warnings {
}
package "aulos.chord" as aulos.chord {
}
package "aulos.note" as aulos.note {
}
package "aulos.note._base" as aulos.note._base {
}
package "aulos.note.key" as aulos.note.key {
}
package "aulos.note.note" as aulos.note.note {
}
package "aulos.note.pitchclass" as aulos.note.pitchclass {
}
package "aulos.scale" as aulos.scale {
}
package "aulos.scale._base" as aulos.scale._base {
}
package "aulos.scale.mode" as aulos.scale.mode {
}
package "aulos.scale.scale" as aulos.scale.scale {
}
package "aulos.tuner" as aulos.tuner {
}
package "aulos.tuner._base" as aulos.tuner._base {
}
package "aulos.tuner.tuner" as aulos.tuner.tuner {
}
package "aulos.utils" as aulos.utils {
}
package "aulos.utils.context" as aulos.utils.context {
}
aulos --> aulos._core
aulos --> aulos._version
aulos --> aulos.note
aulos --> aulos.utils
aulos._core --> aulos._core.object
aulos._core --> aulos._core.setting
aulos._core.context --> aulos._core.context._inject
aulos._core.interfaces --> aulos._core.interfaces.ring
aulos._core.object --> aulos._core.coexistence
aulos._core.object --> aulos._core.schema
aulos._core.object --> aulos._core.setting
aulos._core.schema --> aulos._core.coexistence
aulos._core.shared --> aulos._core.shared.intervals
aulos._core.utils --> aulos._core.utils.array
aulos._core.utils --> aulos._core.utils.calculation
aulos._core.utils --> aulos._core.utils.decorators
aulos._core.utils --> aulos._core.utils.dict
aulos.note --> aulos.note.key
aulos.note --> aulos.note.pitchclass
aulos.note.key --> aulos.note._base
aulos.note.note --> aulos.note._base
aulos.note.pitchclass --> aulos.note._base
aulos.scale --> aulos.scale.mode
aulos.scale --> aulos.scale.scale
aulos.scale.mode --> aulos.scale._base
aulos.scale.mode --> aulos.scale.scale
aulos.scale.scale --> aulos.scale._base
aulos.tuner --> aulos.tuner.tuner
aulos.tuner.tuner --> aulos.tuner._base
aulos.utils --> aulos.utils.context
aulos._core.schema ..> aulos._core.setting
@enduml
