name: Python CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: '${{ matrix.python-version }}'
      
      - name: Test with pytest
        run: |
          uv run --frozen pytest ./tests/aulos --cov=./src/aulos --cov-report=xml
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true
      
      - name: Lint with ruff
        run: |
          uv run --frozen ruff check ./src/aulos ./tests/aulos
      
      - name: Type-check with mypy
        run: |
          uv run --frozen mypy ./src/aulos
