name: Python CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup the Python
        uses: ./.github/actions/setup_python
        with:
          python-version: '${{ matrix.python-version }}'
      
      - name: Test with pytest
        run: |
          python -m pytest ./tests/aulos --cov=./src/aulos --cov-report=xml
    
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup the Python
        uses: ./.github/actions/setup_python
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Lint with ruff
        run: |
          python -m ruff check ./src/aulos ./tests/aulos
  
  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: Setup the Python
        uses: ./.github/actions/setup_python
        with:
          python-version: '${{ matrix.python-version }}'
    
      - name: Type-check with mypy
        run: |
          python -m mypy ./src/aulos

  notify:
    needs: [test, lint, typecheck]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check job status
        run: |
          if [ "${{ needs.test.result }}" = "failure" ] || [ "${{ needs.lint.result }}" = "failure" ] || [ "${{ needs.typecheck.result }}" = "failure" ]; then
            echo "Some jobs failed."
            exit 1
          else
            echo "All jobs completed successfully!"
          fi
