name: Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('./requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install dependencies
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          if [ -f ./requirements-dev.txt ]; then pip install -r ./requirements-dev.txt; fi
      
      - name: Install local packages
        run: |
          python -m pip install -e .
      
      - name: Lint with ruff
        run: |
          alias ruff=/opt/hostedtoolcache/Python/${{ matrix.python-version }}/x64/bin/ruff
          ruff check ./src/aulos ./tests/aulos
      
      - name: Type-check with mypy
        run: |
          alias mypy=/opt/hostedtoolcache/Python/${{ matrix.python-version }}/x64/bin/mypy
          mypy ./src/aulos
      
      - name: Test with pytest
        run: |
          alias pytest=/opt/hostedtoolcache/Python/${{ matrix.python-version }}/x64/bin/pytest
          pytest ./tests/aulos --cov=./src/aulos --cov-report=xml
  
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
