name: 🦀 Rust Tests Workflow

on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened]

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release --verbose

      - name: Test
        run: cargo test --verbose
